"""Classical fluid mechanics submodule."""

from .core import ControlSurface, ControlVolume, FlowField, FluidProperties
from .equations import (
    ResidualOperator,
    continuity_equation,
    euler_equations,
    navier_stokes_equations,
    vorticity_transport_equation,
    energy_equation,
)
from .constitutive import (
    NewtonianStress,
    PowerLawViscosity,
    BinghamPlastic,
    FourierHeatConduction,
    MixingLengthClosure,
    eddy_viscosity_algebraic,
)
from .dimensionless import (
    DimensionlessGroup,
    reynolds_number,
    mach_number,
    prandtl_number,
    nusselt_number,
    froude_number,
    strouhal_number,
    similarity_parameters,
    verify_similarity,
    nondimensionalize_equations,
)
from .solutions import (
    AnalyticalSolution,
    couette_flow,
    poiseuille_flow,
    hagen_poiseuille_flow,
    stokes_first_problem,
    potential_source,
    potential_sink,
    potential_vortex,
    potential_doublet,
    blasius_boundary_layer,
)
from .theorems import (
    TheoremResult,
    reynolds_transport,
    bernoulli,
    kelvin_circulation,
    momentum_balance,
    energy_balance,
)
from .validation import (
    Diagnostic,
    check_mass_conservation,
    check_momentum_conservation,
    check_boundary_condition,
    check_positive_dissipation,
    check_control_volume_mass,
)

__all__ = [
    "ControlSurface",
    "ControlVolume",
    "FlowField",
    "FluidProperties",
    "ResidualOperator",
    "continuity_equation",
    "euler_equations",
    "navier_stokes_equations",
    "vorticity_transport_equation",
    "energy_equation",
    "NewtonianStress",
    "PowerLawViscosity",
    "BinghamPlastic",
    "FourierHeatConduction",
    "MixingLengthClosure",
    "eddy_viscosity_algebraic",
    "DimensionlessGroup",
    "reynolds_number",
    "mach_number",
    "prandtl_number",
    "nusselt_number",
    "froude_number",
    "strouhal_number",
    "similarity_parameters",
    "verify_similarity",
    "nondimensionalize_equations",
    "AnalyticalSolution",
    "couette_flow",
    "poiseuille_flow",
    "hagen_poiseuille_flow",
    "stokes_first_problem",
    "potential_source",
    "potential_sink",
    "potential_vortex",
    "potential_doublet",
    "blasius_boundary_layer",
    "TheoremResult",
    "reynolds_transport",
    "bernoulli",
    "kelvin_circulation",
    "momentum_balance",
    "energy_balance",
    "Diagnostic",
    "check_mass_conservation",
    "check_momentum_conservation",
    "check_boundary_condition",
    "check_positive_dissipation",
    "check_control_volume_mass",
]
